# Используем базовый образ с Node.js
FROM node:14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта в текущую директорию
COPY . /app/

# Устанавливаем зависимости
RUN npm install
RUN npm axios

