version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    image: app
    container_name: drf
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000


  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - psql:/var/lib/postgresql/data



  node:
    build: ./frontend_react
    # имя контейнера
    container_name: reactapp
    # порты
    ports:
      - 3000:3000
    # команда при запуске
    command: npm start
    # зависимость
    depends_on:
      - app
# создаём два volume для статики
volumes:
  django_static_volume:
  django_media_volume:
  psql: